import { open } from './lib';
const ROLL = process.argv[2];
const PORT = process.argv[3] ?? '1275';
const b = await open(ROLL, PORT);
const { ev, send } = b;
await b.waitReady();
let pass = 0, fail = 0;
const ok = (name: string, cond: boolean, extra: any = '') => { if (cond) pass++; else { fail++; console.log('FAIL', name, extra); } };
const nav = async () => { await send('Page.navigate', { url: `http://localhost:${PORT}/?api=remote` }); await Bun.sleep(1000); await b.waitReady(); await Bun.sleep(500); };
const open_ = async () => { await ev(`document.getElementById('columns-btn').click()`); await Bun.sleep(400); };
const click = async (id: string) => { await ev(`document.querySelector('#columns-panel .dd-opt[data-id="${id}"]').click()`); await Bun.sleep(400); };
const cells = async () => ({ head: await ev(`document.querySelector('#table-head tr').children.length`), body: await ev(`(() => { const r = [...document.querySelectorAll('#table-body > tr')].find(t => t.children.length > 3); return r ? r.children.length : -1; })()`) });
await ev(`localStorage.clear(); state.activeTab = 'All'; state.filters = {}; state.hiddenCols = new Set(); render(); 1`); await Bun.sleep(600);
const keys: string[] = await ev(`menuColumns().map(c => c.key)`);
const total = keys.length;
ok('menu has use, ticker first', keys[0] === 'use' && keys[1] === 'ticker' && total === (await ev('CATALOG_COLUMNS.length')) + 1, keys.slice(0, 3));
ok('menu visible on the catalog', await ev(`!document.getElementById('columns-root').hidden`));
ok('summary all', (await ev(`document.getElementById('columns-summary').textContent`)) === `${total} of ${total}`);
const c0 = await cells(); ok('cells match at start', c0.head === c0.body && c0.head === total + 1, c0);
await open_();
ok('one row per column', (await ev(`document.querySelectorAll('#columns-panel .dd-opt').length`)) === total);
ok('two locked rows', (await ev(`document.querySelectorAll('#columns-panel .dd-locked[aria-disabled="true"]').length`)) === 2);
ok('numbers are aligned', (await ev(`new Set([...document.querySelectorAll('#columns-panel .dd-opt .dd-num')].slice(0, 6).map(n => Math.round(n.getBoundingClientRect().right))).size`)) === 1);
await click('ticker'); await ev(`document.querySelector('#columns-panel [data-act="none"]').click()`); await Bun.sleep(500);
ok('Clear keeps use and ticker', (await ev(`state.hiddenCols.size`)) === total - 2, await ev(`state.hiddenCols.size`));
ok('ticker header stays', await ev(`[...document.querySelectorAll('#table-head tr:first-child th')].some(th => getComputedStyle(th).display !== 'none' && /Ticker/i.test(th.textContent))`));
await ev(`document.querySelector('#columns-panel [data-act="reset"]').click()`); await Bun.sleep(400);
ok('Reset shows all', (await ev(`state.hiddenCols.size`)) === 0);
const mid = keys[3], last = keys[total - 1];
await click(mid); await click(last);
const vis = await ev(`[...document.querySelectorAll('#table-head tr:first-child th')].filter(th => getComputedStyle(th).display !== 'none').length`);
ok('two columns hidden in the header', vis === total + 1 - 2, vis);
const c1 = await cells(); ok('cells still match', c1.head === c1.body, c1);
ok('hidden cell is not displayed', (await ev(`(() => { const r = [...document.querySelectorAll('#table-body > tr')].find(t => t.children.length > 3); return getComputedStyle(r.children[4]).display; })()`)) === 'none');
// a filter on a hidden column gives the same rows
await ev(`state.hiddenCols = new Set(); state.filters = { catalog: { aumValue: '>1B' } }; render(); 1`); await Bun.sleep(500);
const shown = await ev(`catalogIds().length`);
await ev(`state.hiddenCols = new Set(['aumValue']); render(); 1`); await Bun.sleep(500);
ok('filter on a hidden column gives the same rows', (await ev(`catalogIds().length`)) === shown && shown > 0, shown);
await ev(`state.filters = {}; state.hiddenCols = new Set(); render(); 1`);
await open_(); await click(mid); await nav();
ok('hidden column persisted after reload', await ev(`state.hiddenCols.has('${mid}') && state.hiddenCols.size === 1`));
ok('summary after reload', (await ev(`document.getElementById('columns-summary').textContent`)) === `${total - 1} selected`);
const c2 = await cells(); ok('cells match after reload', c2.head === c2.body, c2);
const tabOk = await ev(`(() => { try { state.selected.add(store.keys[0]); state.activeTab = 'watchlist'; render(); return document.getElementById('column-visibility-style').textContent === '' && document.getElementById('columns-root').hidden; } catch (e) { return String(e); } })()`);
ok('watchlist: no hidden cells, no menu', tabOk === true, tabOk);
await ev(`state.selected.clear(); state.activeTab = 'All'; state.hiddenCols = new Set(); persistViewFilters(); render(); 1`); await Bun.sleep(400);
await b.shot(process.argv[4] ?? '/tmp/hub-columns.png');
console.log(`${pass} passed, ${fail} failed; console errors: ${b.logs.length ? b.logs.slice(0, 4).join(' | ') : 'none'}`);
b.close(); process.exit(fail || b.logs.length ? 1 : 0);
