/// <reference types="bun" />
import { readFileSync } from 'node:fs';
const reg = JSON.parse(readFileSync(new URL('./registry.json', import.meta.url), 'utf8'));
const feed: Record<string, string> = { 'SP-Funds': './api/spfunds', 'Global-X': './api/globalx', 'First-Trust': './api/firsttrust', 'Goldman-Sachs': './api/goldmansachs', 'Northern-Trust': './api/northerntrust', 'Capital-Group': './api/capital-group' };
for (const r of reg) {
  const f = feed[r.repo] ?? `./api/${r.repo.toLowerCase()}`;
  let src = r.source.replace(/\s+\+\s+/g, ', ').replace(/^Official /, 'official ');
  let d = `${r.brand.replace(/ ETFs$/, '')} ETF holdings-to-watchlist: static ${f} feed generated by a Bun updater from ${src}`;
  if (d.length > 350) d = d.slice(0, 347).replace(/[,\s]+\S*$/, '') + '...';
  console.log(JSON.stringify({ repo: r.repo, desc: d, home: r.pagesUrl, len: d.length }));
}
